menu:
  首页: /
  文章: /archives
  # 友链: /links
  # 实验室: /lab
  # 书单: /books
  # 分类: /category
  关于: /about

excerpt_link: 阅读全文 >

rss: /atom.xml

avatar: "https://avatars0.githubusercontent.com/u/745181?v=2&s=460"

share: true

comment_provider: duoshuo
# Duoshuo comment
duoshuo:
  short_name: zhuxinyong

auto_excerpt:
  enable: true
  length: 150